version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: local-default-db
    restart: always
    ports:
      - '${MYSQL_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: local-default-db-webgui
    restart: always
    ports:
      - '${PMA_PORT}:80'
    environment:
      PMA_HOST: mysql

  redis:
    image: redis:5.0.5
    container_name: local-chaching-db
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    ports:
      - '${REDIS_PORT}:6379'
